version: '3.8'

services:
  pact-broker:
    image: pactfoundation/pact-broker:latest
    container_name: pact-broker
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_URL: postgres://pact:pact@pact-postgres/pact
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: 5
      PACT_BROKER_BASE_URL: ${PACT_BROKER_BASE_URL:-http://localhost:9292}
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http,https
      PACT_BROKER_DISABLE_SSL_VERIFICATION: "true"
      # Basic auth (optional, remove for no auth)
      PACT_BROKER_BASIC_AUTH_USERNAME: ${PACT_BROKER_USERNAME:-pact}
      PACT_BROKER_BASIC_AUTH_PASSWORD: ${PACT_BROKER_PASSWORD:-pact}
      # Public read-only access (optional)
      PACT_BROKER_ALLOW_PUBLIC_READ: "true"
    depends_on:
      - pact-postgres
    networks:
      - pact-network

  pact-postgres:
    image: postgres:15-alpine
    container_name: pact-postgres
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
      POSTGRES_DB: pact
    volumes:
      - pact-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pact"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pact-network

  # Optional: Pact Stub Service for mocking
  pact-stub:
    image: pactfoundation/pact-stub-server:latest
    container_name: pact-stub
    ports:
      - "8080:8080"
    volumes:
      - ./web/frontend/pacts:/pacts:ro
    command: ["-p", "8080", "-d", "/pacts"]
    networks:
      - pact-network

volumes:
  pact-postgres-data:

networks:
  pact-network:
    driver: bridge